function stats = tcOriStats(data, alpha)
%TCORISTATS Kenichi's orientation statistics
%STATS = TCORISTATS(DATA, ALPHA) where DATA is cell array of length NCELLS
%and DATA{IC} is (double) array of size [NTRIALS,NSTIMPLUSONE]

if nargin < 2 
    alpha = 0.05;
end

printflag_for_interp=0;
printflag_for_fitting=0;

[ncells]=length(data);

for icell=1:ncells
    disp(icell)
    
    this = data{icell};
        
    [ntrials,nstimplus]=size(this);
    
    nstim = nstimplus - 1;

    temp=sum(this);
    
    stat.data_table=this;
    stat.dir_ratio_change = temp(1:nstim)/temp(nstim+1)-1; % ratio change
    stat.ori_ratio_change = sum(reshape (stat.dir_ratio_change, nstim/2, 2)')/2;

    % anova
    [stat.p_value_resp,...
        stat.misc.anova_table_resp,...
        stat.misc.anova_stats_resp,...
        stat.misc.sig_epochs_resp] = anova1mult (this, alpha);

    [stat.p_value_sel,...
        stat.misc.anova_table_sel,...
        stat.misc.anova_stats_sel,...
        stat.misc.sig_epochs_sel] = anova1mult (this(:,1:nstim,:), alpha);

    temp = (this(:,1:nstim/2) + this(:,nstim/2+1:nstim))/2;
    temp=[temp,this(:,nstim+1)];
    
    [stat.p_value_ori_resp,...
        stat.misc.anova_table_ori_resp,...
        stat.misc.anova_stats_ori_resp,...
        stat.misc.sig_epochs_ori_resp] = anova1mult (temp, alpha);
    [stat.p_value_ori_sel,...
        stat.misc.anova_table_ori_sel,...
        stat.misc.anova_stats_ori_sel,...
        stat.misc.sig_epochs_ori_sel]  = anova1mult (temp(:,1:nstim/2), alpha);
    % classical analysis
    [stat.best_dir,...
        stat.null_dir,...
        stat.R_best_dir,...
        stat.R_null_dir,...
        stat.R_min_dir,...
        stat.DI]...
            = dir_indexKO(stat.dir_ratio_change);
    [stat.best_ori,...
        stat.null_ori,...
        stat.R_best_ori,...
        stat.R_null_ori,...
        stat.R_min_ori,...
        stat.OI]...
            = dir_indexKO(stat.ori_ratio_change);
    
    % vector average analysis

    [stat.dir_vector_angle,...
        stat.dir_vector_mag,...
        stat.dir_vector_tune]...
        = vector_average(stat.dir_ratio_change);

    [stat.ori_vector_angle,...
        stat.ori_vector_mag,...
        stat.ori_vector_tune]...
        = vector_average(stat.ori_ratio_change);
   
    stat.ori_vector_angle = stat.ori_vector_angle /2;

    % clay's dot product analysis
    
    [stat.best_dir_dp,...
        stat.null_dir_dp,...
        stat.R_best_dir_dp,... 
        stat.R_null_dir_dp,...
        stat.DI_dp]...
        = clayDI (stat.dir_ratio_change, stat.ori_vector_angle);
    
    % kenichi's interpolate analysis
    [stat.best_dir_interp,...
        stat.null_dir_interp,...
        stat.R_best_dir_interp,...
        stat.R_null_dir_interp,...
        stat.DI_interp] = interp_dir_tuningKO (stat.dir_ratio_change,'fourier',printflag_for_interp);

   
    % swindale's tuning curve fitting
    if stat.p_value_sel < alpha
        [stat.best_dir_fit,...
                stat.null_dir_fit,...
                stat.R_best_dir_fit,...
                stat.R_null_dir_fit,...
                stat.DI_fit,...
                stat.DS,...
                stat.dir_tuning_width,...
                stat.dir_A1,...
                stat.dir_A2,...
                stat.misc.dir_k1,...
                stat.misc.dir_k2,... 
                stat.misc.dir_phi2,...
                stat.misc.dir_A,...
                stat.misc.dir_resnorm]...
                = estimate_dir_tuningKO (stat.dir_ratio_change,1,'spline',printflag_for_fitting);
        [stat.best_ori_fit,...
                stat.ori_tuning_width,...
                stat.ori_A1,...
                stat.misc.ori_k1,...
                stat.misc.ori_A,...
                stat.misc.ori_resnorm]...
                = estimate_ori_tuningKO (stat.ori_ratio_change, 1, 'spline',printflag_for_fitting);
    else
        stat.best_dir_fit =NaN;
        stat.null_dir_fit =NaN;
        stat.R_best_dir_fit =NaN;
        stat.R_null_dir_fit =NaN;
        stat.DI_fit =NaN;
        stat.DS =NaN;
        stat.dir_tuning_width =NaN;
        stat.dir_A1 =NaN;
        stat.dir_A2 =NaN;
        stat.misc.dir_k1 =NaN;
        stat.misc.dir_k2 =NaN; 
        stat.misc.dir_phi2 =NaN;
        stat.misc.dir_A =NaN;
        stat.misc.dir_resnorm =NaN;
        stat.best_ori_fit =NaN;
        stat.ori_tuning_width =NaN;
        stat.ori_A1 =NaN;
        stat.misc.ori_k1 =NaN;
        stat.misc.ori_A =NaN;
        stat.misc.ori_resnorm = NaN;
    end
  
    if find_pair_in_list(stat.misc.sig_epochs_sel, [stat.best_dir, stat.null_dir]);
        stat.dir_sig =1;
    else
        stat.dir_sig =0;
    end
    
    stats(icell)=stat;
end

return;